---
title: "How to use viewmastR with large query objects"
output: html_document
date: "2024-02-14"
always_allow_html: true
editor_options: 
  chunk_output_type: console
---


```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
rm(list=ls())
if(grepl("^gizmo", Sys.info()["nodename"])){
  ROOT_DIR1<-"/fh/fast/furlan_s/experiments/MB_10X_5p/cds"
  ROOT_DIR2<-"/fh/fast/furlan_s/grp/data/ddata/BM_data"
} else {
  ROOT_DIR1<-"/Users/sfurlan/Library/CloudStorage/OneDrive-SharedLibraries-FredHutchinsonCancerCenter/Furlan_Lab - General/experiments/MB_10X_5p/cds"
  ROOT_DIR2<-"/Users/sfurlan/Library/CloudStorage/OneDrive-SharedLibraries-FredHutchinsonCancerCenter/Furlan_Lab - General/datasets/Healthy_BM_greenleaf"
}
```


## Installing Rust

First you need to have an updated Rust installation. Go to this [site](https://www.rust-lang.org/tools/install) to learn how to install Rust.


## Installing viewmastR

You will need to have the devtools package installed...

```{r, eval=F}
devtools::install_github("furlan-lab/viewmastR")
```


## Running viewmastR

```{r, dpi=300, fig.height=4, fig.width = 6}
suppressPackageStartupMessages({
library(viewmastR)
library(Seurat)
library(ggplot2)
})

#query dataset
seu <- readRDS(file.path(ROOT_DIR1, "240813_final_object.RDS"))
#reference dataset
seur<-readRDS(file.path(ROOT_DIR2, "230329_rnaAugmented_seurat.RDS"))
vg <- get_selected_genes(seu)
```

## Build the model
```{r}
output_list <- viewmastR(seur, ref_celldata_col = "SFClassification", selected_genes = vg, return_type = "list", backend = "candle", max_epochs = 4, large_query = T)

```


## Appendix
```{r Appendix}
sessionInfo()
getwd()
```
