# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_viewmastR_wrappers", use_symbols = TRUE, package_name = "viewmastR")

#' @usage NULL
#' @useDynLib viewmastR, .registration = TRUE
NULL

#' Read an R object
#' @export
#' @keywords internal
readR <- function(obj) invisible(.Call(wrap__readR, obj))

#' Compute sparse row variance
#' @export
#' @keywords internal
computeSparseRowVariances <- function(j, val, rm, n) .Call(wrap__computeSparseRowVariances, j, val, rm, n)

#'@export
#'@keywords internal
fit_deconv <- function(sigs, bulk, gene_lengths, w_vec, backend, insert_size, init_log_exp, lr, l1_lambda, l2_lambda, max_iter, poll_interval, ll_tol, sparsity_tol, verbose) .Call(wrap__fit_deconv, sigs, bulk, gene_lengths, w_vec, backend, insert_size, init_log_exp, lr, l1_lambda, l2_lambda, max_iter, poll_interval, ll_tol, sparsity_tol, verbose)

#'@export
#'@keywords internal
fit_deconvolution_em <- function(sigs, bulk, gene_lengths, gene_weights, max_iter, tolerance, l1_lambda, verbose) .Call(wrap__fit_deconvolution_em, sigs, bulk, gene_lengths, gene_weights, max_iter, tolerance, l1_lambda, verbose)

infer_from_model <- function(model_path, query, num_classes, num_features, model_type, hidden1, hidden2, verbose, batch_size, backend, num_threads) .Call(wrap__infer_from_model, model_path, query, num_classes, num_features, model_type, hidden1, hidden2, verbose, batch_size, backend, num_threads)

#' A *single* entry-point that covers MLR and ANN/ANN-2L.
#'
#' * `model_type` – `"mlr"`, `"ann"`, or `"ann2"` (you can choose any tokens you like)
#' * `hidden_size` – `NULL` for MLR; numeric (len 1 or 2) for ANN.
#' @export
#' @keywords internal
process_learning_obj <- function(model_type, train, test, query, labels, feature_names, hidden_size, learning_rate, num_epochs, directory, verbose, backend) .Call(wrap__process_learning_obj, model_type, train, test, query, labels, feature_names, hidden_size, learning_rate, num_epochs, directory, verbose, backend)

#' Process Robj learning objects for MLR
#' @export
#' @keywords internal
process_learning_obj_nb <- function(train, test, query) .Call(wrap__process_learning_obj_nb, train, test, query)

#'@export
#'@keywords internal
splat_bulk_reference_rust <- function(counts_matrix, universe, sizes, bandwidth, n_cells_per_bulk, replace_counts, seed, verbose) .Call(wrap__splat_bulk_reference_rust, counts_matrix, universe, sizes, bandwidth, n_cells_per_bulk, replace_counts, seed, verbose)


# nolint end
