# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_viewmastR_wrappers", use_symbols = TRUE, package_name = "viewmastR")

#' @docType package
#' @usage NULL
#' @useDynLib viewmastR, .registration = TRUE
NULL

#' Run full mnist training in R
#' @export
#' @keywords internal
run_mnist_terminal <- function() invisible(.Call(wrap__run_mnist_terminal))

#' Run full mnist training in R; for Rstudio
#' @export
#' @keywords internal
run_mnist <- function() invisible(.Call(wrap__run_mnist))

#' Run full mnist training in R; for Rstudio
#' @export
#' @keywords internal
run_mnist_ann <- function() invisible(.Call(wrap__run_mnist_ann))

#' Read an R object
#' @export
#' @keywords internal
readR <- function(obj) invisible(.Call(wrap__readR, obj))

#' Compute sparse row variance
#' @export
#' @keywords internal
computeSparseRowVariances <- function(j, val, rm, n) .Call(wrap__computeSparseRowVariances, j, val, rm, n)

#' Process Robj learning objects for ANN
#' @export
#' @keywords internal
process_learning_obj_ann <- function(train, test, query, labels, hidden_size, learning_rate, num_epochs, directory, verbose, backend) .Call(wrap__process_learning_obj_ann, train, test, query, labels, hidden_size, learning_rate, num_epochs, directory, verbose, backend)

#' Process Robj learning objects for MLR
#' @export
#' @keywords internal
process_learning_obj_mlr <- function(train, test, query, labels, learning_rate, num_epochs, directory, verbose, backend) .Call(wrap__process_learning_obj_mlr, train, test, query, labels, learning_rate, num_epochs, directory, verbose, backend)

#' Process Robj learning objects for ANN
#' @export
#' @keywords internal
test_backend <- function() invisible(.Call(wrap__test_backend))

#' infer from saved model
#' @export
#' @keywords internal
infer_from_model <- function(model_path, query, num_classes, num_features) .Call(wrap__infer_from_model, model_path, query, num_classes, num_features)


# nolint end
